# super user permissions required for docker
sudo: required
services:
  - docker
# what to run before installing
before_install:
  - docker build -t ozkhan/docker_react -f Dockerfile.dev .
script:
  - docker run -e CI=true ozkhan/docker_react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker_react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-415095052881'
  bucket_path: 'docker_react'
  on:
    branch: master
  access_key_id:
    secure: '$AWS_ACCESS_KEY'
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
